version: '3'
services:
  jenkins:
    image: "dineshsonachalam/jenkins:2.0.0"
    user: root
    networks:
      - frontend
    restart: always
    volumes:
      - ./JENKINS_DATA:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"


networks:
  frontend:
